{
 "title": "Analytics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation_interval", "label": "Time Interval", "query": "1m,5m,15m,30m,1h,6h,12h,1d,30d" }
  ]
 },
 "panels": [
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks/${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_block_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transaction_count\" or r[\"_field\"] == \"milestone_count\" or r[\"_field\"] == \"tagged_data_count\" or r[\"_field\"] == \"no_payload_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: true)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Transaction Payloads/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_block_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"confirmed_count\" or r[\"_field\"] == \"conflicting_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: true)\r\n  |> yield(name: \"sum\")\r\n  "
    }
   ]
  },
  { "title": "Outputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_outputs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"basic_count\" or r[\"_field\"] == \"alias_count\" or r[\"_field\"] == \"nft_count\" or r[\"_field\"] == \"foundry_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tokens Held by Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_outputs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"basic_amount\" or r[\"_field\"] == \"foundry_amount\" or r[\"_field\"] == \"nft_amount\" or r[\"_field\"] == \"alias_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Addresses and Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "import \"strings\"\r\nimport \"math\"\r\n\r\nfrom(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_amount_0\" or r[\"_field\"] == \"total_amount_1\" or r[\"_field\"] == \"total_amount_10\" or r[\"_field\"] == \"total_amount_11\" or r[\"_field\"] == \"total_amount_12\" or r[\"_field\"] == \"total_amount_13\" or r[\"_field\"] == \"total_amount_14\" or r[\"_field\"] == \"total_amount_15\" or r[\"_field\"] == \"total_amount_2\" or r[\"_field\"] == \"total_amount_3\" or r[\"_field\"] == \"total_amount_4\" or r[\"_field\"] == \"total_amount_5\" or r[\"_field\"] == \"total_amount_6\" or r[\"_field\"] == \"total_amount_7\" or r[\"_field\"] == \"total_amount_8\" or r[\"_field\"] == \"total_amount_9\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> map(fn: (r) => ({r with _field: string(v: math.pow10(n: int(v: strings.split(v: r._field, t: \"_\")[2])) / 1000000.0)}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\") "
    }
   ]
  },
  {
   "title": "Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"address_count_0\" or r[\"_field\"] == \"address_count_1\" or r[\"_field\"] == \"address_count_10\" or r[\"_field\"] == \"address_count_11\" or r[\"_field\"] == \"address_count_12\" or r[\"_field\"] == \"address_count_13\" or r[\"_field\"] == \"address_count_14\" or r[\"_field\"] == \"address_count_15\" or r[\"_field\"] == \"address_count_2\" or r[\"_field\"] == \"address_count_3\" or r[\"_field\"] == \"address_count_4\" or r[\"_field\"] == \"address_count_5\" or r[\"_field\"] == \"address_count_6\" or r[\"_field\"] == \"address_count_7\" or r[\"_field\"] == \"address_count_8\" or r[\"_field\"] == \"address_count_9\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SMR Tokens Booked/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_base_token_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"booked_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "SMR Tokens Transferred/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_base_token_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transferred_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Addresses with Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"address_with_balance_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Number of Daily Active Addresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_active_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")\r\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  { "title": "Output Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Alias Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_output_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"alias_created_count\" or r[\"_field\"] == \"alias_governor_changed_count\" or r[\"_field\"] == \"alias_state_changed_count\" or r[\"_field\"] == \"alias_destroyed_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "NFT Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_output_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"nft_created_count\" or r[\"_field\"] == \"nft_destroyed_count\" or r[\"_field\"] == \"nft_transferred_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Foundry Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_output_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"foundry_created_count\" or r[\"_field\"] == \"foundry_destroyed_count\" or r[\"_field\"] == \"foundry_transferred_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: false)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Transaction Distribution by Consumed Outputs /${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_transaction_size_distribution\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"input_0\" or r[\"_field\"] == \"input_1\" or r[\"_field\"] == \"input_2\" or r[\"_field\"] == \"input_3\" or r[\"_field\"] == \"input_4\" or r[\"_field\"] == \"input_5\" or r[\"_field\"] == \"input_6\" or r[\"_field\"] == \"input_7\" or r[\"_field\"] == \"input_huge\" or r[\"_field\"] == \"input_large\" or r[\"_field\"] == \"input_medium\" or r[\"_field\"] == \"input_small\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Transaction Distribution by Created Outputs /${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_transaction_size_distribution\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"output_0\" or r[\"_field\"] == \"output_1\" or r[\"_field\"] == \"output_2\" or r[\"_field\"] == \"output_3\" or r[\"_field\"] == \"output_4\" or r[\"_field\"] == \"output_5\" or r[\"_field\"] == \"output_6\" or r[\"_field\"] == \"output_7\" or r[\"_field\"] == \"output_huge\" or r[\"_field\"] == \"output_large\" or r[\"_field\"] == \"output_medium\" or r[\"_field\"] == \"output_small\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Unlock Conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Number of Unlock Conditions by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_unlock_conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"timelock_count\" or r[\"_field\"] == \"storage_deposit_return_count\" or r[\"_field\"] == \"expiration_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tokens Held by Outputs with Unlock Conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_unlock_conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"expiration_amount\" or r[\"_field\"] == \"storage_deposit_return_amount\" or r[\"_field\"] == \"timelock_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Amount in Storage Deposit Return Unlock Condition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_unlock_conditions\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"storage_deposit_return_inner_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "IOTA Claiming Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Unclaimed Tokens",
   "type": "timeseries",
   "description": "Tokens from the genesis snapshot that have not been claimed yet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_unclaimed_rewards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"unclaimed_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Number of Unclaimed IOTA Genesis Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_unclaimed_rewards\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"unclaimed_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Byte Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Ledger Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_size\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_key_bytes\" or r[\"_field\"] == \"total_data_bytes\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Total Storage Deposit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_size\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_storage_deposit_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}