--- build/tmp_wasp/Dockerfile	2022-09-18 10:17:04.357438835 +0000
+++ wasp-cli/Dockerfile	2022-09-18 10:19:20.530863804 +0000
@@ -7,7 +7,6 @@
 ARG BUILD_TARGET="./..."
 
 WORKDIR /wasp
-RUN mkdir waspdb
 
 # Make sure that modules only get pulled when the module file has changed
 COPY go.mod go.sum ./
@@ -17,8 +16,8 @@
 # Project build stage
 COPY . .
 
-
 RUN go build -o . -tags=${BUILD_TAGS} -ldflags="${BUILD_LD_FLAGS}" ${BUILD_TARGET}
+RUN cd tools/wasp-cli && go build -o . -tags=${BUILD_TAGS} -ldflags="${BUILD_LD_FLAGS}" ${BUILD_TARGET}
 
 ############################
 # Image
@@ -27,19 +26,10 @@
 # using distroless cc "nonroot" image, which includes everything in the base image (glibc, libssl and openssl)
 FROM gcr.io/distroless/cc-debian11:nonroot
 
-ARG FINAL_BINARY="wasp"
+ARG FINAL_BINARY="wasp-cli"
 
-EXPOSE 7000/tcp
-EXPOSE 9090/tcp
-EXPOSE 5550/tcp
-EXPOSE 6060/tcp
-EXPOSE 4000/udp
+WORKDIR /workdir
 
-# Copy the app dir into distroless image
 COPY --chown=nonroot:nonroot --from=build /wasp/${FINAL_BINARY} /usr/bin/
-COPY --chown=nonroot:nonroot --from=build /wasp/waspdb /waspdb
-
-WORKDIR /usr/bin/
-USER nonroot
 
-ENTRYPOINT ["/usr/bin/wasp"]
\ No newline at end of file
+ENTRYPOINT ["/usr/bin/wasp-cli"]
