{
 "title": "Analytics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "aggregation_interval", "label": "Time Interval", "query": "1m,5m,15m,30m,1h,6h,12h,1d,30d" }
  ]
 },
 "panels": [
  { "title": "Blocks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Blocks/${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_block_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"transaction_count\" or r[\"_field\"] == \"milestone_count\" or r[\"_field\"] == \"tagged_data_count\" or r[\"_field\"] == \"no_payload_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: true)\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Transaction Payloads/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_block_activity\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"confirmed_count\" or r[\"_field\"] == \"conflicting_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: sum, createEmpty: true)\r\n  |> yield(name: \"sum\")\r\n  "
    }
   ]
  },
  { "title": "Outputs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Number of Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_outputs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"basic_count\" or r[\"_field\"] == \"alias_count\" or r[\"_field\"] == \"nft_count\" or r[\"_field\"] == \"foundry_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: true)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Tokens Held by Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_outputs\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"basic_amount\" or r[\"_field\"] == \"foundry_amount\" or r[\"_field\"] == \"nft_amount\" or r[\"_field\"] == \"alias_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Addresses and Tokens", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Token Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "import \"strings\"\r\nimport \"math\"\r\n\r\nfrom(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_amount_0\" or r[\"_field\"] == \"total_amount_1\" or r[\"_field\"] == \"total_amount_10\" or r[\"_field\"] == \"total_amount_11\" or r[\"_field\"] == \"total_amount_12\" or r[\"_field\"] == \"total_amount_13\" or r[\"_field\"] == \"total_amount_14\" or r[\"_field\"] == \"total_amount_15\" or r[\"_field\"] == \"total_amount_2\" or r[\"_field\"] == \"total_amount_3\" or r[\"_field\"] == \"total_amount_4\" or r[\"_field\"] == \"total_amount_5\" or r[\"_field\"] == \"total_amount_6\" or r[\"_field\"] == \"total_amount_7\" or r[\"_field\"] == \"total_amount_8\" or r[\"_field\"] == \"total_amount_9\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> map(fn: (r) => ({r with _field: string(v: math.pow10(n: int(v: strings.split(v: r._field, t: \"_\")[2])) / 1000000.0)}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\") "
    }
   ]
  },
  {
   "title": "Address Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"address_count_0\" or r[\"_field\"] == \"address_count_1\" or r[\"_field\"] == \"address_count_10\" or r[\"_field\"] == \"address_count_11\" or r[\"_field\"] == \"address_count_12\" or r[\"_field\"] == \"address_count_13\" or r[\"_field\"] == \"address_count_14\" or r[\"_field\"] == \"address_count_15\" or r[\"_field\"] == \"address_count_2\" or r[\"_field\"] == \"address_count_3\" or r[\"_field\"] == \"address_count_4\" or r[\"_field\"] == \"address_count_5\" or r[\"_field\"] == \"address_count_6\" or r[\"_field\"] == \"address_count_7\" or r[\"_field\"] == \"address_count_8\" or r[\"_field\"] == \"address_count_9\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "SMR Tokens Booked/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Number of Booked SMR Tokens",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_base_token_activity",
     "select": [
      [
       { "params": [ "booked_amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SMR Tokens Transferred/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Number of Transferred SMR Tokens",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_base_token_activity",
     "select": [
      [
       { "params": [ "transferred_amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Addresses with Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_addresses\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"address_with_balance_count\")\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Number of Daily Active Addresses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "alias": "Addresses",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" }
     ],
     "measurement": "stardust_daily_active_addresses",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Output Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Alias Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_output_activity",
     "select": [
      [
       { "params": [ "alias_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "alias_governor_changed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Governor Changed" ], "type": "alias" }
      ],
      [
       { "params": [ "alias_state_changed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "State Changed" ], "type": "alias" }
      ],
      [
       { "params": [ "alias_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "NFT Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_output_activity",
     "select": [
      [
       { "params": [ "nft_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_transferred_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Transferred" ], "type": "alias" }
      ],
      [
       { "params": [ "nft_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Foundry Activity Counts/$aggregation_interval",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_output_activity",
     "select": [
      [
       { "params": [ "foundry_created_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Created" ], "type": "alias" }
      ],
      [
       { "params": [ "foundry_transferred_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Transferred" ], "type": "alias" }
      ],
      [
       { "params": [ "foundry_destroyed_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Destroyed" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Distribution by Consumed Outputs /${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_transaction_size_distribution",
     "query": "SELECT last(\"input_0\"), last(\"input_1\"), last(\"input_2\"), last(\"input_3\"), last(\"input_4\"), last(\"input_5\"), last(\"input_6\"), last(\"input_7\"), last(\"input_small\"), last(\"input_medium\"), last(\"input_large\"), last(\"input_huge\") FROM \"stardust_transaction_size_distribution\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "input_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "input_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "2" ], "type": "alias" }
      ],
      [
       { "params": [ "input_3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "3" ], "type": "alias" }
      ],
      [
       { "params": [ "input_4" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "4" ], "type": "alias" }
      ],
      [
       { "params": [ "input_5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5" ], "type": "alias" }
      ],
      [
       { "params": [ "input_6" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "6" ], "type": "alias" }
      ],
      [
       { "params": [ "input_7" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "alias" }
      ],
      [
       { "params": [ "input_small" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[8..16)" ], "type": "alias" }
      ],
      [
       { "params": [ "input_medium" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[16..32)" ], "type": "alias" }
      ],
      [
       { "params": [ "input_large" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[32..64)" ], "type": "alias" }
      ],
      [
       { "params": [ "input_huge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[64..128)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction Distribution by Created Outputs /${aggregation_interval}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_transaction_size_distribution",
     "query": "SELECT last(\"output_1\"), last(\"output_2\"), last(\"output_3\"), last(\"output_4\"), last(\"output_5\"), last(\"output_6\"), last(\"output_7\"), last(\"output_small\"), last(\"output_medium\"), last(\"output_large\"), last(\"output_huge\") FROM \"stardust_transaction_size_distribution\" WHERE $timeFilter GROUP BY time($aggregation_interval) fill(null)",
     "select": [
      [
       { "params": [ "output_1" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "1" ], "type": "alias" }
      ],
      [
       { "params": [ "output_2" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "2" ], "type": "alias" }
      ],
      [
       { "params": [ "output_3" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "3" ], "type": "alias" }
      ],
      [
       { "params": [ "output_4" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "4" ], "type": "alias" }
      ],
      [
       { "params": [ "output_5" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "5" ], "type": "alias" }
      ],
      [
       { "params": [ "output_6" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "6" ], "type": "alias" }
      ],
      [
       { "params": [ "output_7" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "7" ], "type": "alias" }
      ],
      [
       { "params": [ "output_small" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[8..16)" ], "type": "alias" }
      ],
      [
       { "params": [ "output_medium" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[16..32)" ], "type": "alias" }
      ],
      [
       { "params": [ "output_large" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[32..64)" ], "type": "alias" }
      ],
      [
       { "params": [ "output_huge" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "[64..128)" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Unlock Conditions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Number of Unlock Conditions by Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$col Unlock Conditions",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_unlock_conditions",
     "select": [
      [
       { "params": [ "timelock_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Timelock" ], "type": "alias" }
      ],
      [
       { "params": [ "storage_deposit_return_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Storage Deposit Return" ], "type": "alias" }
      ],
      [
       { "params": [ "expiration_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Expiration" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tokens Held by Outputs with Unlock Conditions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "alias": "$col Unlock Conditions",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_unlock_conditions",
     "select": [
      [
       { "params": [ "timelock_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "Timelock" ], "type": "alias" }
      ],
      [
       { "params": [ "storage_deposit_return_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "Storage Deposit Return" ], "type": "alias" }
      ],
      [
       { "params": [ "expiration_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" },
       { "params": [ "Expiration" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  { "title": "Shimmer Claiming Rewards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Unclaimed Tokens",
   "type": "timeseries",
   "description": "Tokens from the genesis snapshot that have not been claimed yet.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "alias": "Unclaimed Tokens",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_unclaimed_rewards",
     "select": [
      [
       { "params": [ "unclaimed_amount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of Unclaimed Shimmer Genesis Outputs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Unclaimed outputs",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_unclaimed_rewards",
     "select": [
      [
       { "params": [ "unclaimed_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Byte Cost", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Ledger Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col Bytes",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_ledger_size",
     "select": [
      [
       { "params": [ "total_key_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Key" ], "type": "alias" }
      ],
      [
       { "params": [ "total_data_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Data" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Storage Deposit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"stardust_ledger_size\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total_storage_deposit_amount\")\r\n  |> map(fn: (r) => ({r with _value: r._value / 1000000}))\r\n  |> aggregateWindow(every: ${aggregation_interval}, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Amount in Storage Deposit Return Unlock Condition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "SMR" } },
   "targets": [
    {
     "alias": "Return Amount",
     "groupBy": [
      { "params": [ "$aggregation_interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "stardust_unlock_conditions",
     "select": [
      [
       {
        "params": [
         "storage_deposit_return_inner_amount"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}