{
 "title": "Chronicle",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Last Sync Milestone Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"analytics_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"milestone_index\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")\r\n  "
    }
   ]
  },
  {
   "title": "Last Analytics Milestone Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sync_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"milestone_index\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Difference between Sync and Analytics Index",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "Milestone Sync Time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"chronicle\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"sync_metrics\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"milestone_time\")"
    }
   ]
  },
  {
   "title": "MongoDB Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_totalSize{database=\"chronicle\"}",
     "legendFormat": "{{ database }}"
    }
   ]
  },
  {
   "title": "MongoDB Index Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexSize{database=\"chronicle\"}",
     "legendFormat": "Total database: {{ database }}"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_ledger_update_index",
     "legendFormat": "Ledger Update Index"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_output_spent_index",
     "legendFormat": "{{ collection }}"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_block_referenced_index",
     "legendFormat": "Referenced Block Index"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_output_booked_milestone_index",
     "legendFormat": "Output Booked Index"
    },
    {
     "expr": "mongodb_collstats_storageStats_indexSizes_id",
     "legendFormat": "Id Index: {{ collection }}"
    }
   ]
  },
  {
   "title": "Chronicle Mongo Database Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "mongodb_collstats_storageStats_size{database=\"chronicle\"}",
     "legendFormat": "{{ collection }}"
    }
   ]
  }
 ]
}