version: '3'
services:

  iota-core:
    image: iotaledger/iota-core:${IOTA_CORE_VERSION:?IOTA_CORE_VERSION is missing}
    container_name: nova-iotacore
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 5m
    depends_on:
      traefik:
        condition: service_started
    working_dir: /app
    ports:
      - "${IOTA_CORE_GOSSIP_PORT:-15600}:${IOTA_CORE_GOSSIP_PORT:-15600}/tcp"
    labels:
      - "traefik.enable=true"
      - "proxy.constraint=iota-core-${IOTA_CORE_NETWORK:-mainnet}"

      # api
      - "traefik.http.routers.iota-core-api.service=iota-core-api"
      - "traefik.http.routers.iota-core-api.rule=Host(`${IOTA_CORE_HOST:?IOTA_CORE_HOST is missing}`) && (Path(`/health`) || Path(`/api`) || PathPrefix(`/api`))"
      - "traefik.http.routers.iota-core-api.entrypoints=websecure"
      - "traefik.http.routers.iota-core-api.tls=true"
      - "traefik.http.routers.iota-core-api.tls.certresolver=myresolver"

      - "traefik.http.services.iota-core-api.loadbalancer.server.port=14265"
      - "traefik.http.services.iota-core-api.loadbalancer.healthCheck.path=/api/core/v3/info"
      - "traefik.http.services.iota-core-api.loadbalancer.healthCheck.interval=15s"
      - "traefik.http.services.iota-core-api.loadbalancer.healthCheck.timeout=5s"
    cap_drop:
      - ALL
    command:
      - "--config=/app/config.json"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${IOTA_CORE_DATA_DIR:-./data}/config/config-${IOTA_CORE_NETWORK:-mainnet}.json:/app/config.json:ro"
      - "${IOTA_CORE_DATA_DIR:-./data}/config/peering-${IOTA_CORE_NETWORK:-mainnet}.json:/app/peering.json:ro"
      - "${IOTA_CORE_DATA_DIR:-./data}/database/${IOTA_CORE_NETWORK:-mainnet}:/app/data/database"
      - "${IOTA_CORE_DATA_DIR:-./data}/snapshots/${IOTA_CORE_NETWORK:-mainnet}:/app/data/snapshots"
      - "${IOTA_CORE_DATA_DIR:-./data}/p2p/${IOTA_CORE_NETWORK:-mainnet}:/app/data/p2p"
    healthcheck:
      test: ["CMD", "/app/iota-core", "tools", "node-info"]
      interval: 10s
      timeout: 5s
      retries: 60
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  ##################################################################
  #  Reverse Proxy and SSL                                         #
  ##################################################################

  traefik:
    image: traefik:v2.9.8
    container_name: nova-iotacore.traefik
    restart: unless-stopped
    env_file:
      - .env
    command:
      - "--log.level=WARN"
      - "--metrics.prometheus=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`proxy.constraint`,`iota-core-${IOTA_CORE_NETWORK:-mainnet}`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=10"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=10"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${IOTA_CORE_HTTP_PORT:-80}:80/tcp"
      - "${IOTA_CORE_HTTPS_PORT:-443}:443/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${IOTA_CORE_DATA_DIR:-./data}/letsencrypt:/letsencrypt"
      - "./assets/traefik:/etc/traefik/dynamic:ro"
      - "${IOTA_CORE_SSL_CERT:-./assets/traefik/certs/fake.cert}:/certs/domain.cert:ro"
      - "${IOTA_CORE_SSL_KEY:-./assets/traefik/certs/fake.key}:/certs/domain.key:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  ##################################################################
  #  Monitoring                                                    #
  ##################################################################

  prometheus:
    image: prom/prometheus:latest
    container_name: nova-iotacore.prometheus
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_started
    user: "65532"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./assets/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${IOTA_CORE_DATA_DIR:-./data}/prometheus/:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    profiles:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  cadvisor:
    container_name: nova-iotacore.cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    command:
      - --housekeeping_interval=30s    # kubernetes default args
      - --max_housekeeping_interval=35s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      - --store_container_labels=false
      - --global_housekeeping_interval=30s
      - --event_storage_event_limit=default=0
      - --event_storage_age_limit=default=0
      - --disable_metrics=advtcp,cpu_topology,disk,hugetlb,memory_numa,percpu,referenced_memory,resctrl,sched,tcp,udp
      - --enable_load_reader=true
      - --docker_only=true          # only show stats for docker containers
      - --allow_dynamic_housekeeping=true
      - --storage_duration=1m0s
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: nova-iotacore.grafana
    restart: unless-stopped
    user: "65532"
    labels:
      - "proxy.constraint=iota-core-${IOTA_CORE_NETWORK:-mainnet}"
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${IOTA_CORE_HOST:?IOTA_CORE_HOST is missing}`) && (Path(`/grafana`) || PathPrefix(`/grafana/`))"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    environment:
      - GF_SERVER_DOMAIN=${IOTA_CORE_HOST}
      - GF_SERVER_ROOT_URL=/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/local_dashboard.json
    volumes:
      - ./assets/grafana/:/etc/grafana/
      - ${IOTA_CORE_DATA_DIR:-./data}/grafana:/var/lib/grafana
    profiles:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  ##################################################################
  #  INX Extensions                                                #
  ##################################################################

  inx-indexer:
    image: iotaledger/inx-indexer:${INX_INDEXER_VERSION:?INX_INDEXER_VERSION is missing}
    container_name: nova-iotacore.inx-indexer
    stop_grace_period: 5m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_healthy
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    volumes:
      - "${IOTA_CORE_DATA_DIR:-./data}/database/${IOTA_CORE_NETWORK:-mainnet}:/app/database"
    command:
      - "--inx.address=iota-core:9029"
      - "--indexer.db.sqlite.path=/app/database/indexer"
      - "--restAPI.bindAddress=inx-indexer:9091"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-indexer:9312"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  inx-mqtt:
    image: iotaledger/inx-mqtt:${INX_MQTT_VERSION:?INX_MQTT_VERSION is missing}
    container_name: nova-iotacore.inx-mqtt
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_healthy
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
    command:
      - "--inx.address=iota-core:9029"
      - "--mqtt.websocket.bindAddress=inx-mqtt:1888"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-mqtt:9312"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  inx-dashboard:
    image: iotaledger/inx-dashboard:${INX_DASHBOARD_VERSION:?INX_DASHBOARD_VERSION is missing}
    container_name: nova-iotacore.inx-dashboard
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_started
    labels:
      - "proxy.constraint=iota-core-${IOTA_CORE_NETWORK:-mainnet}"
      - "traefik.enable=true"

      - "traefik.http.services.iota-core-dashboard.loadbalancer.server.port=8081"
      - "traefik.http.services.iota-core-dashboard.loadbalancer.healthCheck.path=/"
      - "traefik.http.services.iota-core-dashboard.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.iota-core-dashboard.loadbalancer.healthCheck.timeout=3s"

      - "traefik.http.routers.iota-core-dashboard.service=iota-core-dashboard"
      - "traefik.http.routers.iota-core-dashboard.rule=Host(`${IOTA_CORE_HOST:?IOTA_CORE_HOST is missing}`)"
      - "traefik.http.routers.iota-core-dashboard.entrypoints=websecure"
      - "traefik.http.routers.iota-core-dashboard.tls=true"
      - "traefik.http.routers.iota-core-dashboard.tls.certresolver=myresolver"

      - "traefik.http.routers.iota-core-dashboard.middlewares=security-headers,redirect-dashboard"

      # middlewares
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.regex=^(https?://[^/]+)/?$$"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.replacement=$$1/dashboard/"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.permanent=true"

      - "traefik.http.middlewares.security-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.security-headers.headers.customResponseHeaders.Access-Control-Allow-Origin=https://${IOTA_CORE_HOST:?IOTA_CORE_HOST is missing}:${IOTA_CORE_HTTPS_PORT:-443}"
      - "traefik.http.middlewares.security-headers.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.security-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${IOTA_CORE_DATA_DIR:-./data}/dashboard/${IOTA_CORE_NETWORK:-mainnet}:/app/dashboard"
    command:
      - "--logger.level=debug"
      - "--inx.address=iota-core:9029"
      - "--dashboard.bindAddress=inx-dashboard:8081"
      - "--dashboard.explorerURL=https://explorer.iota.org/iota2-testnet"
      - "--dashboard.auth.identityFilePath=/app/dashboard/identity.key"
      - "--dashboard.auth.username=${INX_DASHBOARD_USERNAME}"
      - "--dashboard.auth.passwordHash=${INX_DASHBOARD_PASSWORD}"
      - "--dashboard.auth.passwordSalt=${INX_DASHBOARD_SALT}"
      - "--prometheus.enabled=true"
      - "--prometheus.bindAddress=inx-dashboard:9312"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  inx-blockissuer:
    image: iotaledger/inx-blockissuer:${INX_BLOCKISSUER_VERSION:?INX_BLOCKISSUER_VERSION is missing}
    container_name: nova-iotacore.inx-blockissuer
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_healthy
      inx-indexer:
        condition: service_started
    environment:
      - "BLOCKISSUER_PRV_KEY=${INX_BLOCKISSUER_PRV_KEY:-}"
    command:
      - "--inx.address=iota-core:9029"
      - "--restAPI.bindAddress=inx-blockissuer:9086"
      - "--blockIssuer.accountAddress=${INX_BLOCKISSUER_ACCOUNT_ADDR:-}"
      - "--blockIssuer.proofOfWork.targetTrailingZeros=25"
    profiles:
      - blockissuer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  inx-validator:
    image: iotaledger/inx-validator:${INX_VALIDATOR_VERSION:?INX_VALIDATOR_VERSION is missing}
    container_name: nova-iotacore.inx-validator
    stop_grace_period: 1m
    restart: unless-stopped
    depends_on:
      iota-core:
        condition: service_started
    environment:
      - "VALIDATOR_PRV_KEY=${INX_VALIDATOR_PRV_KEY:-}"
    command:
      - "--logger.level=debug"
      - "--inx.address=iota-core:9029"
      - "--validator.accountAddress=${INX_VALIDATOR_ACCOUNT_ADDR:-}"
    profiles:
      - validator
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  default:
    name: nova
    external: true
