name: Build wasp-cli docker image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "wasp-cli version"
        required: true

jobs:
  build:
    name: Build and push wasp-cli image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          ./build.sh --wasp-cli-image ${{  github.event.inputs.version }} --skip-docker-builder
